// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOARqxHddLgkucEg_ApVPIBrK44AULhSA',
    appId: '1:166985861887:web:92aaa3f68eceb6ca0adaca',
    messagingSenderId: '166985861887',
    projectId: 'sport-event-72e46',
    authDomain: 'sport-event-72e46.firebaseapp.com',
    storageBucket: 'sport-event-72e46.appspot.com',
    measurementId: 'G-H7YMTTN05J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd_IoF8WLnlqBZ3G9Sem9FXQwn_QQcOjM',
    appId: '1:166985861887:android:63cd3f21a0d0cf750adaca',
    messagingSenderId: '166985861887',
    projectId: 'sport-event-72e46',
    storageBucket: 'sport-event-72e46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVi6TeSlt5-igazdozl3XycxnJFpu0Jsk',
    appId: '1:166985861887:ios:fc506f8ef6d157170adaca',
    messagingSenderId: '166985861887',
    projectId: 'sport-event-72e46',
    storageBucket: 'sport-event-72e46.appspot.com',
    androidClientId:
        '166985861887-4546d3irragmg8mm11re5518obt30ha7.apps.googleusercontent.com',
    iosClientId:
        '166985861887-r2u3f9na8aj7cjfifu6pus4ccqpn8hnt.apps.googleusercontent.com',
    iosBundleId: 'com.siran.sportEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVi6TeSlt5-igazdozl3XycxnJFpu0Jsk',
    appId: '1:166985861887:ios:fc506f8ef6d157170adaca',
    messagingSenderId: '166985861887',
    projectId: 'sport-event-72e46',
    storageBucket: 'sport-event-72e46.appspot.com',
    androidClientId:
        '166985861887-4546d3irragmg8mm11re5518obt30ha7.apps.googleusercontent.com',
    iosClientId:
        '166985861887-r2u3f9na8aj7cjfifu6pus4ccqpn8hnt.apps.googleusercontent.com',
    iosBundleId: 'com.siran.sportEvents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOARqxHddLgkucEg_ApVPIBrK44AULhSA',
    appId: '1:166985861887:web:8a2a0715fba0375e0adaca',
    messagingSenderId: '166985861887',
    projectId: 'sport-event-72e46',
    authDomain: 'sport-event-72e46.firebaseapp.com',
    storageBucket: 'sport-event-72e46.appspot.com',
    measurementId: 'G-7EVM95ZK29',
  );
}
